# Generated by Django 5.1.1 on 2024-10-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="bboard",
            options={
                "ordering": ["-published"],
                "verbose_name": "Реклама",
                "verbose_name_plural": "Рекламы",
            },
        ),
        migrations.AlterField(
            model_name="bboard",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bboard",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bboard",
            name="title",
            field=models.CharField(max_length=50, verbose_name="название рекламы"),
        ),
        migrations.AddField(
            model_name="bboard",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.category",
            ),
        ),
    ]
