# Generated by Django 5.1.1 on 2024-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookin_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="rooms",
            field=models.ManyToManyField(
                related_name="amenities", to="bookin_service.room"
            ),
        ),
    ]
